version: '3.2'

services:

  frontend:
    image: abiosoft/caddy
    environment:
      - CADDYPATH=/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - ./docker/caddy/caddyssl:/etc/caddycerts
      - .:/app
    depends_on:
      - backend

  backend:
    image: wbc-tt:backend
    build:
      context: .
      dockerfile: docker/phalcon/Dockerfile-prod
    volumes:
      # temporary mount assets to frontend
      - .public:/app/public
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=wbc
      - MYSQL_USER=wbc
      - MYSQL_PASSWORD=verysecret
