<div class="page-header">
    <h1>Congratulations!</h1>
</div>

<p>You're now logged in!</p>

<form action="/logout" method="post">
    <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
           value='<?php echo $this->security->getToken() ?>'/>
    <div class="row">
        <div class="col-sm-6">
            <button class="btn btn-lg btn-primary btn-block" type="submit">Logout</button>
        </div>
    </div>
</form>